name: CI

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build_and_test:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: CI -- lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: CI -- test
        uses: actions-rs/cargo@v1
        with:
          command: test
      
      - name: CI -- format
        uses: actions-rs/cargo@v1
        with:
          command: fmt