name: CI

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build_and_test:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable 18 months ago
      
      - name: CI -- lint
        run: |
          cargo clippy

      - name: CI -- test
        run: |
          cargo test
      
      - name: CI -- format
        run: |
          cargo fmt